- name: disable current version of mysql
  ansible.builtin.command: dnf install disable mysql -y

- name: setup mysql5.7repo
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Install mysql server
  ansible.builtin.package:
    name: mysql-community-server
    state: present

- name: start and enable mysql
  ansible.builtin.service:
    name: mysql
    state: restarted
    enabled: yes

- name: setup root password 
  ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1